spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git: 
          uri: https://github.com/sagarlavale/olx-config
          username: sagarlavale
          password: 
          clone-on-start: true
server:
  port: 8888
  